spring.application.name=campannas

spring.datasource.url=jdbc:postgresql://localhost:5432/farmacia_ahumada_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=30MB

server.port=8080